 -- **************** TRIGGERS CORRELATIVO DE RETENCION DE IVA *******************************
--
-- ********************************************************************************
-- ***************** JOSE RAVELO ABR-2012 *****************************************
-- PARTE 1: Solo para los casos registrados por CXP / Nota de debito (Normal)
-- ESTE TRIGGER EVALUA LA INCLUSION DE UN REGISTRO EN SAACXP DEL TIPO TIPOCXP 31 REVERSO DE RETENCION IVA X NC
-- Y TENGA CALCULADO VALOR EN RETENIVA, DEBE RECOGER CONSECUTIVO DE RETENCION INCREMENTARLO EN UNO Y GRABARLO 
-- EN SACORREL Y EN EL PROPIO REGISTRO INCLUIDO MAS SU REFERENCIA AFECTADA EN NROPPAL.
-- EN LOS UPDATE DE LAS LINES 4X Y 4X SE DEBE MEJORAR COLOCANDO @POS COMO LONGITUD EN EL SUBSTRING, 
-- EN LA PRIMERA CORRIDA NO FUNCIONO Y TUVE QUE REOLVER PROVISIONALMENTE CON '1'
-- tambien coloca valor de factura afectada en el campo numeron en el registro tipo 31
-- PARTE 2 -- CALCULA Y DESGLOSA DE BI Y TAX DEL MONTO TOTAL REGISTRADO PARA LOS CASOS DE NC/ANTICIPOS
-- NO CONTEMPLA POSIBILIDAD DE GENERAR REVERSOS DE RETENCION esta opcion.
-- APLICA PARA CUALALQUIER TRANSACCION VIEJA O NUEVA PORQUE LEE SATAXCOM TAL Y COMO SE PRODUJO LA TRANSAACION DE ORIGEN.
-- ULTIMA ACTUALIZACION 05/06/2013 EN METROPOLIS SE OPTIMIZA PARTE 2 Y SE COMPLETA DOCUMENTACION.
-- ACTUALIZACION 18/05/2013 EN LIBERTY SE INCLUYEN VALIDACIONES CON MENSAJES  EN PARTE 2
 

DROP TRIGGER [CORRELRETIVA]
GO

CREATE TRIGGER [CORRELRETIVA] ON [dbo].[SAACXP] 
WITH ENCRYPTION
FOR INSERT
AS
SET ANSI_NULLS, QUOTED_IDENTIFIER ON

DECLARE @TIPOCXP   VARCHAR(2)
DECLARE @RETENIVA  DECIMAL(28,3)
DECLARE @NROUNICO  INT
DECLARE @NROREGI   INT
DECLARE @VALUEINT  INT 
DECLARE @LONGCORR  INT
DECLARE @FIELDNAME VARCHAR(25) 
DECLARE @ZEROS VARCHAR (6)
DECLARE @COMPRAAFECTADA VARCHAR(25)
DECLARE @POS INT
DECLARE @MONTO DECIMAL(28,3)
DECLARE @CODOPER VARCHAR(15)
DECLARE @CODPROV VARCHAR(15)
DECLARE @ALICUOTA DECIMAL(28,3)
DECLARE @STATUSERROR INT
DECLARE @DESCRIPERROR VARCHAR(200)
DECLARE @NOTAS1 VARCHAR(20)
DECLARE @FECHATCOM DATETIME
DECLARE @FECHATCRE DATETIME


   SET @ZEROS='000000'
   SET @STATUSERROR=0
   SET @DESCRIPERROR=''

BEGIN

   SELECT @TIPOCXP=TIPOCXP, 
          @RETENIVA=RETENIVA,
          @NROUNICO=NROUNICO,
          @NROREGI=NROREGI, 
          @MONTO=MONTO, 
          @CODOPER=CODOPER,
          @CODPROV=CODPROV,
          @COMPRAAFECTADA=DOCUMENT,
          @NOTAS1=NOTAS1,
          @FECHATCRE=FECHAT
   FROM INSERTED
   
      
    
   -- PARTE 1: SI ES NOTA DE DEBITO CON REVERSO DE RETENCION.
   IF EXISTS (SELECT * FROM SAACXP WHERE TIPOCXP='31' AND RETENIVA>0 and NROUNICO=@NROUNICO)
     BEGIN
     SELECT @COMPRAAFECTADA=NUMERON FROM SAACXP WHERE NROUNICO=@NROREGI
     SELECT @FECHATCOM=FECHAT FROM SAACXP WHERE NUMEROD=@COMPRAAFECTADA AND CODPROV=@CODPROV AND TIPOCXP='10'
     IF YEAR(@FECHATCOM)=YEAR(@FECHATCRE)
       BEGIN
       IF MONTH(@FECHATCOM)=MONTH(@FECHATCRE)
         BEGIN
         IF ((DAY(@FECHATCOM)>=1 AND DAY(@FECHATCOM)<=15 AND DAY(@FECHATCRE)>=1 AND DAY(@FECHATCRE)<=15)) OR  ((DAY(@FECHATCOM)>=16 AND DAY(@FECHATCOM)<=31 AND DAY(@FECHATCRE)>=16 AND DAY(@FECHATCRE)<=31) )   
           BEGIN
   
            SELECT @VALUEINT=VALUEINT FROM SACORRELSIS WHERE FIELDNAME='PRXRETENIVA'
            SET @LONGCORR=LEN(STR(@VALUEINT))
            SET @POS=6-@LONGCORR
      
               
            UPDATE SAACXP SET NUMERON=@COMPRAAFECTADA, NUMEROD = SUBSTRING(@zeros,1,1)+ltrim(str(@valueint)), saldoact=saldoact-monto WHERE NROUNICO=@NROUNICO
            UPDATE SAACXP SET MONTO=MONTONETO+MTOTAX, NUMERODN= SUBSTRING(@zeros,1,1)+ltrim(str(@valueint)) , saldoact=saldoact-reteniva WHERE NROUNICO=@NROREGI 
      
            UPDATE SACORRELSIS SET VALUEINT=VALUEINT+1 WHERE FIELDNAME='PRXRETENIVA'
            
           END
          ELSE
           BEGIN
            SET @STATUSERROR=1
            SET @DESCRIPERROR = 'PARA GENERAR REVERSO DE RETENCION LAS FECHAS DE REGISTRO DE LA COMPRA Y NOTA DE CREDITO DEBEN ESTAR DENTRO DE LA MISMA QUINCENA'
           END
          END
         ELSE
         BEGIN
          SET @STATUSERROR=1
          SET @DESCRIPERROR =   'PARA GENERAR REVERSO DE RETENCION LAS FECHAS DE REGISTRO DE LA COMPRA Y NOTA DE CREDITO DEBEN ESTAR DENTRO DEL MISMO MES Y QUINCENA'
         END     
       END
      ELSE
       BEGIN
        SET @STATUSERROR=1
        SET @DESCRIPERROR =    'PARA GENERAR REVERSO DE RETENCION LAS FECHAS DE REGISTRO DE LA COMPRA Y NOTA DE CREDITO DEBEN ESTAR DENTRO DEL MISMO ANO, MES Y QUINCENA'
       END         
    END 
        
         
   
   -- PARTE 2: SI ES NOTA DE DEBITO TIPO ANTICIPO PARA SER APLICADA EN OTRA FACTURA. valido para cualquier proveedor --  
   
   IF EXISTS (SELECT * FROM SAACXP WHERE TIPOCXP='50' AND CODOPER='06-007' AND NROUNICO=@NROUNICO)
   BEGIN       
     IF  EXISTS (SELECT * FROM SATAXCOM WHERE NUMEROD=@COMPRAAFECTADA AND TIPOCOM='H')
        IF @NOTAS1<>'' AND CONVERT(DATETIME, @NOTAS1, 120) <= getdate()
          BEGIN
           SELECT @ALICUOTA=MTOTAX FROM SATAXCOM WHERE NUMEROD=@COMPRAAFECTADA AND TIPOCOM='H'
           SET @ALICUOTA=@ALICUOTA/100
           UPDATE SAACXP SET FECHAI=CONVERT(DATETIME, @NOTAS1, 120), BASEIMPO=(@MONTO/(1+@ALICUOTA)), MTOTAX=(@MONTO/(1+@ALICUOTA))* @ALICUOTA WHERE NROUNICO=@NROUNICO
          END
        ELSE
         BEGIN
          SET @STATUSERROR=1
          SET @DESCRIPERROR = 'DEBE INDICAR EN EL CAMPO NOTAS1 DE COMENTARIOS LA FECHA VALIDA DEL DOCUMENTO. <<REVISE Y VUELVA A INTENTARLO>>'
         END
     ELSE
       BEGIN
       SET @STATUSERROR=1
       SET @DESCRIPERROR = 'DEBE INDICAR EN EL CAMPO DETALLE UN NUMERO DE FACTURA AFECTADA VALIDA. <<REVISE Y VUELVA A INTENTARLO>>'
       END
   END
   
END   

 IF @STATUSERROR=1
   BEGIN
      RAISERROR (@DESCRIPERROR,16,1)
       ROLLBACK TRANSACTION
      RETURN
   END