DECLARE @cLAVE VARCHAR(10)
DECLARE @SIGUIENTE VARCHAR(10)
DECLARE @ACTUAL VARCHAR(10)
  
DECLARE MIREG CURSOR FOR
      SELECT CLAVE
         FROM dbo.SAFACT_01B AS X ORDER BY CLAVE
      OPEN MIREG
      FETCH NEXT FROM MIREG INTO @CLAVE
      WHILE (@@FETCH_STATUS = 0) 
      BEGIN
         SET @SIGUIENTE=@ACTUAL
         SET @ACTUAL=@CLAVE
         IF @ACTUAL=@SIGUIENTE
            PRINT @aCTUAL
            FETCH NEXT FROM MIREG INTO @CLAVE
      END
      CLOSE MIREG
      DEALLOCATE MIREG

 