DECLARE @CODPROD VARCHAR(10)
DECLARE @SIGUIENTE VARCHAR(10)
DECLARE @ACTUAL VARCHAR(10)
  
DECLARE MIREG CURSOR FOR
      SELECT CODPROD
         FROM dbo.SAPROD_12_01 AS X ORDER BY CODPROD
      OPEN MIREG
      FETCH NEXT FROM MIREG INTO @CODPROD
      WHILE (@@FETCH_STATUS = 0) 
      BEGIN
         SET @SIGUIENTE=@ACTUAL
         SET @ACTUAL=@CODPROD
         IF @ACTUAL=@SIGUIENTE
            PRINT @aCTUAL
            FETCH NEXT FROM MIREG INTO @CODPROD
      END
      CLOSE MIREG
      DEALLOCATE MIREG

 


 

 