 -- QUERY DE LIMPIEZA DE BASE DE DATOS SOLO TRANSACCIONES
-- SE MANTIENEN DATOS EN TABLAS MAESTRAS
-- CASO CONCESIONARIOS de la misma marca
-- ELABORADO POR: JOSE RAVELO / OM System Consulting, C.A.

-- COMPRAS --
DELETE FROM SACOMP
DELETE FROM SAITEMCOM
DELETE FROM SAACXP
DELETE FROM SAPAGCXP
DELETE FROM SATAXCOM
DELETE FROM SATAXITC
DELETE FROM SATAXCXP
DELETE FROM SAECOM
DELETE FROM SAEPRV
DELETE FROM SASEPRCOM
DELETE FROM SACOMP_01
DELETE FROM SACOMP_02

-- VENTAS --

DELETE FROM SAFACT
DELETE FROM SAFACT_01
DELETE FROM SAFACT_02
DELETE FROM SAFACT_03
-- DELETE FROM SAFACT_04 solo con solucion 49 manejo de aseguradoras
DELETE FROM SACFAC
DELETE FROM SACLICNV
DELETE FROM SAITEMFAC
DELETE FROM SAACXC
DELETE FROM SAPAGCXC
DELETE FROM SATAXCXC
DELETE FROM SATAXVTA
DELETE FROM SATAXITF
DELETE FROM SAECLI
DELETE FROM SAEVTA
DELETE FROM SASEPRFAC
DELETE FROM SASE_RETIVACXC
DELETE FROM SAIPAVTA
DELETE FROM SAIPACXC

-- INVENTARIO --

DELETE FROM SAEPRD
DELETE FROM SAEOPI
DELETE FROM SAINITI
DELETE FROM SAOPEI
DELETE FROM SAITEMOPI
DELETE FROM SASEPROPI
DELETE FROM SAEQUI


--SECCION APLICABLE SOLO A CONCESIONARIOS DE DIFERENTES MARCAS
DELETE FROM SAPROD
DELETE FROM SAPROD_11_01
DELETE FROM SAPROD_11_02
DELETE FROM SAPROD_11_03
DELETE FROM SAPROD_11_04
DELETE FROM SAPROD_12_01
DELETE FROM SAPROD_12_02
DELETE FROM SAPROD_12_03




--DELETE FROM SADEPO
DELETE FROM SADEPO_01


-- SERVICIOS --

DELETE FROM SAESRV
--DELETE FROM SASERV
DELETE FROM SATAXSRV


-- VENDEDORES --

DELETE FROM SAEVEN
DELETE FROM SACVEN

-- SERVIDORES --

DELETE FROM SAEMEC
DELETE FROM SACMEC

-- INSTRUMENTOS DE PAGO --

DELETE FROM SAETAR
DELETE FROM SAIPACXC
DELETE FROM SAIPAVTA

-- BANCOS --

DELETE FROM SBDTRN
DELETE FROM SBDIFE
DELETE FROM SBTRAN
DELETE FROM SBCONC  
DELETE FROM SBMONE  


-- TABLAS MAESTRAS

DELETE FROM SAPROD
DELETE FROM SAPROD_11_01
DELETE FROM SAPROD_11_02
DELETE FROM SAPROD_11_03
DELETE FROM SAPROD_11_04
DELETE FROM SAPROD_12_01
DELETE FROM SAPROD_12_02
DELETE FROM SAPROD_12_03
DELETE FROM SACODBAR
DELETE FROM SASERI
DELETE FROM SAEXIS
DELETE FROM SAIPRD
DELETE FROM SACSCODALTVEH
DELETE FROM SATAXPRD

DELETE FROM SACLIE
DELETE FROM SACLIE_01
DELETE FROM SACLIE_02
DELETE FROM SACLIE_03
DELETE FROM SACLIE_04
DELETE FROM SACLIE_05
DELETE FROM SACLIE_06
DELETE FROM SAICLI


DELETE FROM SAPROV
DELETE FROM SAPROV_01
DELETE FROM SAPROV_02
DELETE FROM SAPROV_03
DELETE FROM SAPROV_04
DELETE FROM SAIPRV
DELETE FROM SAPVPR


-- TABLAS ESPECIALES
--DELETE FROM SACORRELSIS

-- OTRSO MAESTROS
--DELETE FROM SAVEND
DELETE FROM SAIVEN
--DELETE FROM SAMECA
DELETE FROM SAIMEC
DELETE FROM SAESTA
DELETE FROM DBTHIRD

-- BANCOS
-- DELETE FROM SBBANC
-- DELETE FROM SBBENE
DELETE FROM SBCONF
DELETE FROM SBCTAS
DELETE FROM SBDESA
DELETE FROM SBDESAB
-- DELETE FROM SBFMTS
DELETE FROM SBPRXC
DELETE FROM SBRPTD
DELETE FROM STIB01
DELETE FROM STIB02
DELETE FROM SBTRTR






-- DELETE FROM SAOPER
DELETE FROM DBTHIRD






