-- ESTE QUERY PASA EL CONTENIDO Y LIMPIA EL CAMPO REFERE
-- REQUISITO PARA NO INCURRIR EN VIOLACION DE CLAVE DUPLICADA EN SACODBAR
-- VALIDADO EN NUEVA VERSION 8642


UPDATE SAPROD SET DESCRIP3=REFERE WHERE REFERE='VEHICULO' OR REFERE='MODELO'

UPDATE SAPROD SET REFERE='' WHERE REFERE='VEHICULO' OR REFERE='MODELO'

-- IMPORTANTE: SOLO EJECUTAR UNA SOLA VEZ
