  -- *****************************************************************************************
-- PROCESA ELIMINAR REGISTRO DE VEHICULO 
 -- *****************************************************************************************

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[SACS_SP_ELIMINA_VEHICULO]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[SACS_SP_ELIMINA_VEHICULO]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE PROCEDURE dbo.SACS_SP_ELIMINA_VEHICULO
  @codprod Varchar(15)
WITH ENCRYPTION
AS

-----------------------------------
-- DECLARACION DE VARIABLES 
-----------------------------------

-- Contenido de campos de safact
DECLARE @SERIAL      Varchar (20),
        @MODELO      Varchar (20),
        @CODOPER     Varchar (2),
        @NUMEROD     Varchar (15),
        @Tipofac     Varchar (1),
        @STATUSERROR INT,
        @DESCRIPERROR VARCHAR(256),
        @CODINST VARCHAR(2)

SELECT @CODINST=CODINST FROM SAPROD WHERE CODPROD=@CODPROD

SELECT @SERIAL=SERIAL FROM SAPROD_12_01 WHERE CODPROD=@CODPROD

SELECT @MODELO=CODPROD FROM SASERI WHERE NROSERIAL=@SERIAL

SELECT @NUMEROD=X.NUMEROD, @TIPOFAC=X.TIPOFAC, @CODOPER=Y.CODOPER FROM SAFACT_01 X INNER JOIN SAFACT Y ON X.NUMEROD=Y.NUMEROD AND X.TIPOFAC=Y.TIPOFAC WHERE X.PLACA=@CODPROD

  -- Valida si al ELIMINAR PRODUCTO CORRESPONDE A UN VEHICULO 

     IF @CODINST='12' 
   
         BEGIN
          
          DELETE SAPROD WHERE CODPROD=@CODPROD
          DELETE SACODBAR WHERE CODPROD=@CODPROD OR CODALTE=@CODPROD OR CODALTE=@SERIAL OR CODALTE=RIGHT(@SERIAL,9) OR CODALTE=RIGHT(@SERIAL,6)
          DELETE SACSCODALTVEH WHERE CODPROD=@CODPROD OR CODALT=@CODPROD OR CODALT=@SERIAL OR CODALT=RIGHT(@SERIAL,9) OR CODALT=RIGHT(@SERIAL,6)
          DELETE SATAXPRD WHERE CODPROD=@CODPROD
          DELETE SAEPRD WHERE CODPROD=@CODPROD
          DELETE SAIPRD WHERE CODPROD=@CODPROD
          DELETE SAEXIS WHERE CODPROD=@CODPROD
         
          DELETE SAPROD_12_01 WHERE CODPROD=@CODPROD  
          DELETE SAPROD_12_02 WHERE CODPROD=@CODPROD
          DELETE SAPROD_12_03 WHERE CODPROD=@CODPROD
          DELETE SAPROD_11_03 WHERE SERIAL=@SERIAL

          IF EXISTS (SELECT * FROM SASERI WHERE NROSERIAL=@SERIAL)
             BEGIN
              DELETE SASERI WHERE NROSERIAL=@SERIAL
              UPDATE SAPROD SET EXISTEN=EXISTEN-1 WHERE CODPROD=@MODELO
              UPDATE SAEXIS SET EXISTEN=EXISTEN-1 WHERE CODPROD=@MODELO   
             END

          SET @STATUSERROR=0
          SET @DESCRIPERROR='<<<<<<< VEHICULO ELIMINADO  >>>>>>>' 
                    
         END  
      
-- MUESTRA PANTALLA CON RESULTADO DE VALIDACIONES SI LAS HAY.

 --  IF @STATUSERROR=1
   --           BEGIN
     --           RAISERROR (@DESCRIPERROR,16,1)
       --         ROLLBACK TRANSACTION
         --       RETURN
           --   END



SET QUOTED_IDENTIFIER OFF 
GO

SET ANSI_NULLS ON 

