 
-- QUERY PARA AJUSTAR MARGEN DE UTILIDAD DE VENTAS DE REPUESTOS
-- SE GARANTIZA QUE LOS PRECIOS MAYORES AL MARGEN DE GANANCIA MINIMO INDICADO se mantengan
-- EN LOS DECIMALES DE LA CONSTANTE @MARGEN SE MANTIENEN Y SOLO SE -- MODIFICAN AQUELLOS QUE ESTEN POR DEBAJO.
-- TAMBIEN SE CONSIDERA LOS 3 COSTOS Y SE AJUSTA EN BASE AL MAS ALTO.
-- SE DEBE MANTENER EL UNO 1 EN EL CONTENIDO DE LA VARIABLE Y SE DEBE IDICAR EN EL DECIMAL LA VARIACION PORCENTUAL DESEADA.
-- EJEMPLO SI SE DESEA EL COSTO+45% SE DEBE INDICAR 1.45.
-- PROGRAMADO Y PROBADO POR JOSE RAVELO MAY 2012
-- 04/12/2012 Orden de Sr. Barroso. Chrysler y Mitsubishi¨:C+65%, Fiat, Lifan, Honda, Mercedes:C+80%
-- por lo que se programa estos valores como precios3 y precios 2 y 1: 10 y 20% menos respectivamente.
-- 10/07/2013 ordenado por cesar barroso en prestige se ajustan precios en costo*2.0, costo*2.1, costo*2.2 en precios 1,2,3 respectivamente.
-- 16/07/2013 SE OPTIMIZA AJUSTANDO REPUESTOS OBSOLETOS, NULOS Y MUY BAJA ROTACION A COSTOX4
-- 11/11/2013 SE OPTIMIZA AGREGANDO FUNCION DE REDONDEO A DECENAS Y RESPALDO DE PRECIO ACTUAL OJO DEBE EJECUTARSE SOLO UNA VEZ
-- 11/11/2013 SE EJECUTA AJUSTANDO A COSTO+33% EN CHRYSLER Y MITSUBISHI, FIAT A 45% Y SURAUTO QUEDA SIN AJUSTE.
-- NO SE ACTUALIZAN VEHICULOS12, MODELOS11, ACCESORIOS4, OBSOLETOS33, INACTIVOS1

DECLARE @MARGEN1 DECIMAL(13,2)
DECLARE @MARGEN2 DECIMAL(13,2)
DECLARE @MARGEN3 DECIMAL(13,2)


SET @MARGEN1=1.30
SET @MARGEN2=1.30
SET @MARGEN3=1.30

-- RESPALDA EL PRECIO3 ACTUAL EN PRECIOU3

--UPDATE    SAPROD  SET   PrecioU3 = Precio3


-- APLICA MARGE MINIMO SUGERIDO 

UPDATE    SAPROD

SET       Precio1 = CostPro * @MARGEN1, Precio2 = CostPro * @MARGEN2, Precio3 = CostPro * @MARGEN3
 
WHERE    (CodInst <> '11') AND (CodInst <> '12') and (CostPro <> 0)  --AND CodInst<>'33' AND (Precio3 < CostPro * @MARGEN3)and  (CodInst<>'4' AND AND (Activo = '1') 



UPDATE    SAPROD

SET       Precio1 = CostAnt * @MARGEN1, Precio2 = CostAnt * @MARGEN2, Precio3 = CostAnt * @MARGEN3

WHERE     (CodInst <> '11') AND (CodInst <> '12')   AND (CostPro <> 0) --AND CodInst<>'33' AND (Precio3 < CostAnt * @MARGEN3) AND (Activo = '1') and (CodInst<>'4' AND



UPDATE    SAPROD

SET       Precio1 = CostAct * @MARGEN1, Precio2 = CostAct * @MARGEN2, Precio3 = CostAct * @MARGEN3 
 
WHERE     ( CodInst <> '11') AND (CodInst <> '12')   AND (CostPro <> 0) --AND CodInst<>'33' AND (Precio3 < CostAct * @MARGEN3)and  (CodInst<>'4' AND AND (Activo = '1') 

-- APLICA REDONDEO A DECENAS EN PRECIO FINAL CON IVA EN BASE AL 12%.

--UPDATE    SAPROD

--SET       Precio1 = ROUND(PRECIO1*1.12,-1)/1.12  , Precio2 = ROUND(PRECIO2*1.12,-1)/1.12 , Precio3 =  ROUND(PRECIO3*1.12,-1)/1.12
 
--WHERE     (CodInst<>'4' AND CodInst <> '11') AND (CodInst <> '12')  AND (Activo = '1')  -- AND CodInst<>'33'


