-- QUERY PARA LA SOLUCION CONSULTA FINANCIERA DE VEHICULOS.
-- PREPARA LA TABLA SAFACT_01 DE DATOS ADICIONALES PARA QUE CONTROLE
-- LAS FACTURAS DE VEHICULOS QUE HAN SIDO DEVUELTAS Y AGREGA EN EL CAMPO 
-- STATUS 'ANULADA' Y LIQUIDACION = NOTA DE CREDITO


UPDATE    SAFACT_01
SET              STATUS = 'ANULADA', LIQUIDACION = SAFACT.NUMEROD
FROM         SAFACT INNER JOIN
                      SAFACT_01 ON SAFACT_01.NumeroD = SAFACT.Notas6 AND SAFACT_01.TipoFac = 'A'
WHERE     (SAFACT.TipoFac = 'B') AND (SAFACT.CodOper = '01-101')