-- ********************************************************************************
-- TRIGGER PARA PROCESAR ELIMINACION DE RETENCIONES IVA PROVEEDOR 
-- ********************************************************************************
-- ***************** JOSE RAVELO NOV-2007 *****************************************
DROP TRIGGER ELIMINA_RETENCION_IVA_PROVEEDOR
GO
CREATE TRIGGER [ELIMINA_RETENCION_IVA_PROVEEDOR] ON [dbo].[SAPROV_01] 
WITH ENCRYPTION
FOR INSERT, UPDATE 
AS


DECLARE @CODPROV VARCHAR(10)
DECLARE @USUARIO VARCHAR(35)
DECLARE @RETENCION VARCHAR(20)
DECLARE @RESULTADO VARCHAR(35)
DECLARE @NROUNICO INT 
DECLARE @NROREGI INT
DECLARE @SALDO INT
DECLARE @MTORETEN INT
DECLARE @COMPRA VARCHAR(20)

BEGIN
SELECT @CODPROV=CODPROV, @USUARIO=USUARIO, @Retencion=Retencion_a_eliminar FROM INSERTED 

IF EXISTS (SELECT * FROM SAACXP WHERE @CODPROV=CODPROV AND @RETENCION = NUMEROD AND TIPOCXP='81')  
   BEGIN
      SELECT @NROUNICO=NROUNICO,@NROREGI=NROREGI, @MTORETEN=MONTO FROM SAACXP WHERE @CODPROV=CODPROV AND @RETENCION = NUMEROD AND TIPOCXP='81'
      SELECT @COMPRA = NUMEROD FROM SAACXP WHERE NROUNICO=@NROREGI 
      UPDATE SAACXP SET RETENIVA=0, SALDO = SALDO + RETENIVA WHERE NROUNICO=@NROREGI
      UPDATE SACOMP SET RETENIVA=0 WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
      DELETE SAPAGCXP WHERE NROPPAL = @NROUNICO
      DELETE SAACXP WHERE NROUNICO=@NROUNICO
      SET @RESULTADO = 'RETENCION IVA ELIMINADA'
   END
   ELSE
   BEGIN
      SET @RESULTADO = 'SOLICITUD NO PROCEDENTE'
   END 

UPDATE SAPROV_01 SET RESULTADO=@RESULTADO WHERE CODPROV=@CODPROV AND @RETENCION=RETENCION_A_ELIMINAR
END