 -- **************** TRIGGERS MODIFICA_FECHAS_EN_COMPRAS ***************************
--
-- ********************************************************************************
-- ***************** JOSE RAVELO MAY-2008 *****************************************
-- ESTE TRIGGER ACTUALIZA LOS REGISTROS DE LAS TABLAS DE VENTAS QUE ALMACENAN FORMAS DE PAGO  
-- 

DROP TRIGGER [MODIFICA_FORMA_DE_PAGO]
GO

CREATE TRIGGER [MODIFICA_FORMA_DE_PAGO] ON [dbo].[SACLIE_05] 
WITH ENCRYPTION
FOR INSERT, UPDATE 
AS

DECLARE @CODCLIE VARCHAR(15)
DECLARE @USUARIO VARCHAR(35)
DECLARE @FACTURA VARCHAR(15)
DECLARE @EFECTIVO INT
DECLARE @CHEQUE INT 
DECLARE @INSTRUMENTO INT
DECLARE @RESULTADO VARCHAR(35)
DECLARE @NUINSERTED INT
DECLARE @MONTO INT
 
BEGIN
SELECT @CODCLIE=CODCLIE, @USUARIO=USUARIO, @FACTURA=FACTURA, @EFECTIVO=EFECTIVO,
       @CHEQUE=CHEQUE, @INSTRUMENTO=INSTRUMENTO_DE_PAGO,@NUINSERTED=NROUNICO, @MONTO=EFECTIVO+CHEQUE+INSTRUMENTO_DE_PAGO
FROM INSERTED

IF EXISTS (SELECT * FROM SAACXC WHERE (NUMEROD=@FACTURA AND CODCLIE=@CODCLIE AND TIPOCXC='41' AND MONTO=@MONTO))

   BEGIN

      UPDATE SAACXC SET CANCELE=@EFECTIVO, CANCELC=@CHEQUE, CANCELT=@INSTRUMENTO WHERE (NUMEROD=@FACTURA AND CODCLIE=@CODCLIE AND TIPOCXC='41' AND MONTO=@MONTO) 
      UPDATE SAFACT SET CANCELE=@EFECTIVO, CANCELC=@CHEQUE, CANCELT=@INSTRUMENTO WHERE (NUMEROD=@FACTURA AND CODCLIE=@CODCLIE AND TIPOFAC='A') 
  

      SET @RESULTADO = 'CAMBIOS  SATISFACTORIOS'
  
   END
   ELSE
   BEGIN
      SET @RESULTADO = 'FACTURA NO VALIDA O MONTO ERRONEO'
   END 

UPDATE SACLIE_05 SET RESULTADO=@RESULTADO WHERE NROUNICO=@NUINSERTED
END