-- *********************************************************************************************************
-- VALIDA CAMBIO EN VALOR DE LA LIQUIDACION CUANDO EXISTEN REPUESTOS CARGADOS. 
-- EXPLICACION: NO SE PERMITE CAMBIAR LA LIQUIDACION CUANDO EXISTEN REPUESTOS Y SERVICIO CARGADOS
-- ORIGINAL AGREGADO EL 26/11/2009 POR: JOSE RAVELO
-- EL 13/03/2013 FUE EVALUADO ESTE TRIGGER PARA MEDIR EL GRADO DE AFECTACION SOBRE
-- MODIFICACION EN RORAIMA POR EL CUAL SE INCORPORA LAS OR GARANTAS FACTURABLES
-- SE CONCLUYE QUE ESTE TRIGGER PRESENTA UNA GENERALIZACION EN SU ACCION QUE LO HACE NO ESPECIFICO POR EL CUAL
-- NO DISCRIMINA LOS POSIBLES CAMBIOS DE LIQUIDACION VALIDOS Y NO VALIDOS IGUAL, PARA LOS CASOS GARANTIA CAMBIA A CONTADO 
-- Y VICEVERSA SITUACION ESTA QUE SERIA VALIDA SEGUN EL NUEVO ESQUEMA.
-- *********************************************************************************************************
--IF OBJECT_ID ('SESA_TG_MODIFICA_LIQUIDACION', 'TG') IS NOT NULL
--DROP TRIGGER SESA_TG_MODIFICA_LIQUIDACION
--GO
 
CREATE TRIGGER SESA_TG_MODIFICA_LIQUIDACION ON SAFACT_01
-- WITH ENCRYPTION
FOR  UPDATE
AS


DECLARE @Tipofac varchar (1),
        @NumeroD varchar (15),
        @CodOper varchar (10),
        @liquidacion Varchar(15),
        @status Varchar(15),
        @LIQANT varchar(30),
        @STATUSERROR INT,
        @DESCRIPERROR VARCHAR(200)
         
        
        
-- RECOGE DATOS DE TABLAS REGISTRO DE LA ORDEN DE REPARACION

    SELECT @LIQUIDACION=LIQUIDACION,
           @STATUS= STATUS,
           @NUMEROD=NUMEROD,
           @TIPOFAC=TIPOFAC
    FROM INSERTED ;  
    
 -- ATENCION EN LA SIGUIETE SE RECOGE EL VALOR DE NOTAS10 QUE ES EL MISMO DE ORDENC
 -- SOLO QUE ALGUNOS CAMPOS ENTRE ELLOS ORDENC TIENE ALGUN SENSOR O CARACTERISTICA POR
 -- ESPECIAL POR LENGUAJE DE LA APLICACION QUE HACE INVIABLE SU USO (APARECE ERROR DE COMANDO)
    
    SELECT @LIQANT=notas10,
           @CODOPER=CODOPER
    FROM   SAFACT
    WHERE  NUMEROD=@NUMEROD AND TIPOFAC=@TIPOFAC
  
   IF @TIPOFAC='G' AND @CODOPER='01-301' -- ES UNA OPERACION DE SERVICIO  
    
   BEGIN
   
     SET @LIQUIDACION='%'+SUBSTRING(@LIQUIDACION,1,4)+'%' --PREPARA LA CADENA A SER BUSCADA EN LA SIGUIENTE INSTRUCCION
        
     IF NOT EXISTS (SELECT * FROM SAFACT WHERE NUMEROD=@NUMEROD AND TIPOFAC=@TIPOFAC AND NOTAS10 LIKE @LIQUIDACION)
 
      BEGIN
       IF EXISTS (SELECT * FROM SAITEMFAC WHERE NUMEROD=@NUMEROD AND TIPOFAC=@TIPOFAC AND ESSERV = 0)
       BEGIN
        RAISERROR (N'NO PUEDE CAMBIAR LIQUIDACION CON REPUESTOS CARGADOS....! TRANSACCION CANCELADA',16,1)
        ROLLBACK TRANSACTION
        RETURN
       END
      END
   END 

   