-- ********************************************************************************
-- TRIGGER PARA PROCESAR ELIMINACION DE COMPRAS Y DOCUMENTOS RELACIONADOS 
-- ********************************************************************************
-- ************************** JOSE RAVELO NOV-2007 ********************************
DROP TRIGGER ELIMINA_COMPRAS
GO
CREATE TRIGGER [ELIMINA_COMPRAS] ON [dbo].[SAPROV_03] 
WITH ENCRYPTION
FOR INSERT, UPDATE 
AS


DECLARE @CODPROV VARCHAR(10)
DECLARE @USUARIO VARCHAR(35)
DECLARE @RESULTADO VARCHAR(35)
DECLARE @NROUNICO INT 
DECLARE @NROREGI INT
DECLARE @NROPPAL INT
DECLARE @SALDO INT
DECLARE @CODOPER VARCHAR(10)
DECLARE @COMPRA VARCHAR(40)
DECLARE @SERIAL VARCHAR(20)
DECLARE @PLACA VARCHAR(15)
DECLARE @FECHA DATETIME
DECLARE @ANO VARCHAR(4)
DECLARE @MES VARCHAR(2)
DECLARE @DIA VARCHAR(2)
DECLARE @PERIODO VARCHAR(6)
DECLARE @PERIODO2 VARCHAR(8)

-- VALIDAR EXISTENCIA DE USUARIO QUE SOLICITA LA ELIMINACION AL MENOS EXISTENCIA A SAUSUario


BEGIN

SELECT @CODPROV=CODPROV, @USUARIO=USUARIO, @COMPRA=Compra_a_eliminar FROM INSERTED 

IF EXISTS (SELECT * FROM SACOMP WHERE @CODPROV=CODPROV AND @COMPRA = NUMEROD AND TIPOCOM='H')  
   BEGIN
     
     -- OJO REVISAR EN VERSION 8642 SI ES FECHAE O FECHAI -- OJO 
     SELECT @NROUNICO=NROUNICO, @CODOPER=CODOPER, @FECHA=FECHAE, @ANO=YEAR(FECHAE), @MES=MONTH(FECHAE)
            FROM SAACXP WHERE CODPROV=@CODPROV AND TIPOCXP='10' AND NUMEROD=@COMPRA

      -- Retenciones IVA, PAGOS, NC Y ND
         SELECT @NROPPAL=NROPPAL FROM SAPAGCXP WHERE NROREGI=@NROUNICO AND TIPOCXP='41'
         DELETE SAACXP WHERE NROUNICO=@NROPPAL AND TIPOCXP='41' AND CODPROV=@CODPROV
         DELETE SAPAGCXP WHERE NROREGI = @NROUNICO
         DELETE SAACXP WHERE NROREGI = @NROUNICO
      -- Existencia e Inventario 
         UPDATE SAEXIS SET EXISTEN=y.EXISTEN-X.CANTIDAD FROM SAITEMCOM x LEFT OUTER JOIN
         SAEXIS y ON x.CodItem = y.CodProd WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV AND X.ESSERV=0)
         UPDATE SAPROD SET EXISTEN=y.EXISTEN-X.CANTIDAD FROM SAITEMCOM x LEFT OUTER JOIN
         SAPROD y ON x.CodItem = y.CodProd WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV AND X.ESSERV=0)

         -- En caso de Vehiculo
            IF @CODOPER='05-101' OR EXISTS(SELECT * FROM SAITEMCOM X INNER JOIN SAPROD Y ON X.CODITEM=Y.CODPROD WHERE Y.CODINST='12')
               BEGIN
                  SELECT @SERIAL=NROSERIAL FROM SASEPRCOM WHERE NumeroD = @COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
                  SELECT @PLACA=CODPROD    FROM SAPROD_12_01 WHERE SERIAL=@SERIAL 
                  DELETE SAPROD WHERE CODPROD=@PLACA
                  DELETE SASERI WHERE NROSERIAL=@SERIAL
                  DELETE SAPROD_12_01 WHERE CODPROD=@PLACA
                  DELETE SAPROD_12_02 WHERE CODPROD=@PLACA -- NUEVA ESTRUCTURA
                  DELETE SAPROD_12_03 WHERE CODPROD=@PLACA -- NUEVA ESTRUCTURA
                  DELETE SASEPRCOM WHERE NumeroD = @COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
                  DELETE SAEXIS WHERE CODPROD=@PLACA
                  DELETE SATAXPRD WHERE CODPROD=@PLACA
                  DELETE SAPROD_11_03 WHERE CODPROD=@PLACA
               END

      -- Servicios 

      -- Estadisticas
         SET @PERIODO=@ANO+@MES 
         SET @PERIODO2=@PERIODO+@DIA

         UPDATE SAESRV SET cntcompra=cntcompra-X.CANTIDAD,mtocompra=mtocompra-X.CANTIDAD*X.COSTO FROM SAITEMCOM x LEFT OUTER JOIN
         SAESRV y ON x.CodItem = y.CodSERV and y.periodo=@periodo WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV AND X.ESSERV=1)
         
         UPDATE SAEPRD SET cntcompra=cntcompra-X.CANTIDAD,mtocompra=mtocompra-X.CANTIDAD*X.COSTO FROM SAITEMCOM x LEFT OUTER JOIN
         SAEPRD y ON x.CodItem = y.CodPROD and y.periodo=@periodo WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV AND X.ESSERV=0)

         UPDATE SAEPRV SET nrocomps=nrocomps-1 FROM SACOMP x LEFT OUTER JOIN
         SAEPRV y ON x.CodPROV = y.CodPROV and y.periodo=@periodo WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV)

         UPDATE SAECOM SET nrocomps=nrocomps-1,mtocompra=mtocompra-X.monto, mtotax=y.mtotax-x.mtotax FROM SACOMP x LEFT OUTER JOIN
         SAECOM y ON y.periodo=@periodo2 WHERE (x.NumeroD = @COMPRA AND X.TIPOCOM='H' AND X.CODPROV=@CODPROV)

      -- Saldos pendientes

      -- Compras - CxP - Impuestos 
         DELETE SACOMP WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SACOMP_01 WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SACOMP_02 WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SAITEMCOM WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SATAXCOM WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SATAXITC WHERE NUMEROD=@COMPRA AND TIPOCOM='H' AND CODPROV=@CODPROV
         DELETE SAACXP WHERE NUMEROD=@COMPRA AND CODPROV=@CODPROV

      -- Resultado del proceso
       
       SET @RESULTADO = 'COMPRA ELIMINADA'
   END
   ELSE
   BEGIN
      SET @RESULTADO = 'SOLICITUD NO PROCEDENTE'
   END 

UPDATE SAPROV_03 SET RESULTADO=@RESULTADO WHERE CODPROV=@CODPROV AND Compra_a_eliminar=@compra
END
