-- ********************************************************************************
-- TRIGGER PARA PROCESAR ELIMINACION DE RETENCIONES EN VENTAS A CONTRIBUYENTES ESPECIALES
-- ********************************************************************************
-- ************************** JOSE RAVELO NOV-2007 ********************************
DROP TRIGGER ELIMINA_RETIVA_VTA
GO
CREATE TRIGGER [ELIMINA_RETIVA_VTA] ON [dbo].[SACLIE_02] 
WITH ENCRYPTION
FOR INSERT, UPDATE 
AS
 
 

DECLARE @CODCLIE VARCHAR(10)
DECLARE @USUARIO VARCHAR(10)
DECLARE @RESULTADO VARCHAR(35)
DECLARE @NROUNICO INT 
DECLARE @NROREGI INT
DECLARE @NROPPAL INT
DECLARE @SALDO DECIMAL(23,2)
DECLARE @CODOPER VARCHAR(10)
DECLARE @RETENCION VARCHAR(14)
DECLARE @FECHA DATETIME
DECLARE @MONTO DECIMAL(23,2)
DECLARE @NUMERON VARCHAR(15)
DECLARE @NUMEROD VARCHAR(15)
 
 
-- VALIDAR EXISTENCIA DE USUARIO QUE SOLICITA LA ELIMINACION AL MENOS EXISTENCIA A SAUSUario


BEGIN

SET @RESULTADO = 'SOLICITUD NO PROCEDENTE'

SELECT @CODCLIE=CODCLIE, @USUARIO=USUARIO, @RETENCION=RETENCION_a_eliminar FROM INSERTED 



IF EXISTS (SELECT * FROM SAACXC WHERE @CODCLIE=CODCLIE AND @RETENCION=NUMEROD AND TIPOCXC='81') 

   BEGIN
       SELECT @NROUNICO=NROUNICO, @NROREGI=NROREGI, @MONTO=MONTO, @NUMERON=NUMERON FROM SAACXC WHERE @CODCLIE=CODCLIE AND @RETENCION= NUMEROD AND TIPOCXC='81'

       DELETE SAIPACXC WHERE NROPPAL=@NROUNICO
 
       DELETE SAPAGCXC WHERE NROPPAL=@NROUNICO
  
       DELETE SAACXC WHERE CODCLIE=@CODCLIE AND NUMEROD=@RETENCION

       DELETE SAACXC WHERE NROUNICO=@NROREGI AND MONTO=0

       UPDATE SAACXC SET SALDO=SALDO+@MONTO WHERE NUMEROD=@NUMERON AND CODCLIE=@CODCLIE AND TIPOCXC='10' 

       UPDATE SAFACT SET RETENIVA=0, NOTAS9='' WHERE NUMEROD=@NUMERON AND CODCLIE=@CODCLIE     

       SET @RESULTADO = 'RETENCION ELIMINADA VIA 81'
   END


IF EXISTS (SELECT * FROM SAACXC WHERE @CODCLIE=CODCLIE AND @RETENCION=DOCUMENT AND TIPOCXC='41') 
   BEGIN

       SELECT @NROUNICO=NROUNICO, @NROREGI=NROREGI, @MONTO=MONTO, @NUMERON=NUMERON FROM SAACXC WHERE @CODCLIE=CODCLIE AND @RETENCION= DOCUMENT AND TIPOCXC='41'
   
       DELETE SASE_RETIVACXC WHERE NROPPAL=@NROUNICO

       DELETE SAIPACXC WHERE NROPPAL=@NROUNICO
 
       DELETE SAPAGCXC WHERE NROPPAL=@NROUNICO
  
       DELETE SAACXC WHERE @CODCLIE=CODCLIE AND @RETENCION= DOCUMENT 

       DELETE SAACXC WHERE NROUNICO=@NROREGI AND MONTO=0

       UPDATE SAACXC SET SALDO=SALDO+@MONTO WHERE NUMEROD=@NUMERON AND CODCLIE=@CODCLIE 

       UPDATE SAFACT SET RETENIVA=0, NOTAS9='' WHERE NUMEROD=@NUMERON AND CODCLIE=@CODCLIE           

       SET @RESULTADO = 'RETENCION ELIMINADA VIA 41'

   END

UPDATE SACLIE_02 SET RESULTADO=@RESULTADO WHERE CODCLIE=@CODCLIE AND RETENCION_a_eliminar=@RETENCION

END


