if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[SASC_PRECIOS_SUGERIDOS]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view dbo.SASC_PRECIOS_SUGERIDOS
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE VIEW dbo.SASC_PRECIOS_SUGERIDOS 
AS SELECT *
FROM dbo.SAPROD_11_04

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

